### ISSUE TITLE
Completion not working

### ISSUE THREAD

**Issue by star-tek-mb** [zigtools/zls-vscode#42]
Hello there!
Completion list is not showing up. And shows bunch of errors on Log (Window):

```
[2022-07-13 22:14:07.098] [renderer1] [error] Cannot read properties of null (reading 'range'): TypeError: Cannot read properties of null (reading 'range')
	at getCompletionRangeAndText (c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\protocolConverter.js:393:35)
	at asCompletionInsertText (c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\protocolConverter.js:367:19)
	at asCompletionItem (c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\protocolConverter.js:298:28)
	at c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\protocolConverter.js:244:20
	at convertBatch (c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\utils\async.js:181:25)
	at Object.map (c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\utils\async.js:190:17)
	at Object.asCompletionResult (c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\protocolConverter.js:243:39)
	at c:\Users\noobtek\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\completion.js:94:62
	at async ne.provideCompletionItems (c:\Users\noobtek\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:51341)
```

Maybe some modules got outdated from package.json. I will investigate further.

**Comment by SuperAuguste** [comment]
Please provide more details; this is quite vague!

**Comment by star-tek-mb** [comment]
I think this is my compiled zls. I tried zls from your new zls_install - it works perfectly. Thanks again for extension!
